---
- name: Testing andrewrothstein.kpt
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'kpt version'
      ansible.builtin.command: kpt version
      changed_when: false
      register: test_kpt_version
    - name: Output from 'kpt version'
      ansible.builtin.debug:
        msg: '{{ test_kpt_version.stdout }}'
